Allow failures on Pypy3
Pypy3's been breaking pretty regularly due to an import error:

    ImportError: cannot import name 'pythonapi'
    make: *** [init] Error 1

Here we (temporarily) allow it to fail in the build matrix so that we
can get the general build back to green.